[Boost] Turn yellow at 60% remaining, and red at 30% remaining
pmndrs/racing-game pull request #166
Opened 2021-07-05 03:13 UTC by bjornstar

The old numbers were based on boost levels that were between 50 and 100.

2021-07-05 10:43 UTC, njm222 requested changes
Looks great! but let's move this out of the ui and into the store?

2021-07-06 00:49 UTC, bjornstar commented
> Looks great! but let's move the hardcoded values out of the ui and into the store?

I gave the values names, but I don't think they need to move into another file as they are only used in this one place.

2021-07-06 00:50 UTC, merged

2021-07-06 05:06 UTC, njm222 commented
> > Looks great! but let's move the hardcoded values out of the ui and into the store?
> 
> I gave the values names, but I don't think they need to move into another file as they are only used in this one place.

Yes it is only being used here but it shouldn't be stored there, but rather passed to it via props or from the store, because it is a ui element and it should be able to change functionality from props. If the boost limits are in the store > vehicleConfig when we have more vehicles with different boost values (maxBoost, criticalLevel & warningLevel) it will work without having to change it again.

2021-07-06 05:36 UTC, bjornstar commented
> Yes it is only being used here but it shouldn't be stored here, but rather passed to it via props or from the store, because it is a ui element and it should be able to change functionality from props. If the boost limits are in the store > vehicleConfig when we have more vehicles with different boost values (maxBoost, criticalLevel & warningLevel) it will work without having to change it again.

Yes, but we don't have more vehicles with different boost values. When the need arises, it can be moved. There's no need to do it right now in this PR.